[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --timeout 30 --log-level info wsgi:application"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
